# Generated by Django 4.0.1 on 2025-01-15 12:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='id',
        ),
        migrations.AddField(
            model_name='destination',
            name='destination_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='http_method',
            field=models.CharField(max_length=10),
        ),
    ]
